# Generated by Django 3.1.4 on 2021-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='MTRANS_Automobile',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='MTRANS_Bike',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='MTRANS_Motorbike',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='MTRANS_Public_Transportation',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='MTRANS_Walking',
        ),
        migrations.AddField(
            model_name='predresults',
            name='means_of_transport',
            field=models.CharField(default='TEST', max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='calories_consumption_monitoring',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='consumption_of_alcohol',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='consumption_of_food_between_meals',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='family_history_with_overweight',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='frequent_consumption_of_high_caloric_food',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='smoke',
            field=models.CharField(max_length=30),
        ),
    ]
